"""empty message

Revision ID: 199e7cf65a7b
Revises: 4e6a0eac3da2
Create Date: 2022-04-19 19:05:20.159001

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '199e7cf65a7b'
down_revision = '4e6a0eac3da2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('name', sa.String(length=40), nullable=False))
    op.create_unique_constraint(None, 'users', ['name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'name')
    # ### end Alembic commands ###
